deployment

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,9 +1,9 @@
-
 pipeline {
     agent any
 
     environment {
-        DOCKER_IMAGE = "zaraki89/jenkins-ci-demo"
+        IMAGE = "zaraki89/jenkins-ci-demo"
+        EC2_HOST = "13.233.102.147"
     }
 
     stages {
@@ -16,9 +16,7 @@ pipeline {
 
         stage('Build Docker Image') {
             steps {
-                script {
-                    sh "docker build -t $DOCKER_IMAGE:${env.BUILD_NUMBER} ."
-                }
+                sh "docker build -t $IMAGE:${env.BUILD_NUMBER} ."
             }
         }
 
@@ -32,21 +30,30 @@ pipeline {
             }
         }
 
-        stage('Push Image to Docker Hub') {
+        stage('Push Image') {
             steps {
-                script {
-                    sh "docker push $DOCKER_IMAGE:${env.BUILD_NUMBER}"
+                sh "docker push $IMAGE:${env.BUILD_NUMBER}"
+            }
+        }
+
+        stage('Deploy to EC2') {
+            steps {
+                sshagent(['ec2-ssh']) {
+                    sh """
+                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST '
+                        docker pull $IMAGE:${env.BUILD_NUMBER} &&
+                        docker stop app || true &&
+                        docker rm app || true &&
+                        docker run -d -p 3000:3000 --name app $IMAGE:${env.BUILD_NUMBER}
+                    '
+                    """
                 }
             }
         }
     }
 
     post {
-        success {
-            echo "Docker Build & Push Successful!"
-        }
-        failure {
-            echo "Build failed!"
-        }
+        success { echo "CI/CD Pipeline Completed Successfully!" }
+        failure { echo "Pipeline Failed!" }
     }
 }
